fix(shortcuts): always unregister global shortcuts before reregistering Fixes an error where I was getting
```
TypeError: window['_3282349814'] is not a function. (In 'window['_3282349814']({ message: {"shortcut":"shift+super+KeyD","id":570425366,"state":"Pressed"}, index: 14 })', 'window['_3282349814']' is undefined)
```

since the old callback registered was somehow being lost on full page refreshes. Unregistering before reregistering fixes this.